Feature/add model and pages
koooommmm/contract-checker pull request #17
Opened 2024-05-05 07:56 UTC by hmatsunobu

# 動かすには

Cloud Storageを使用するためには、CORSの構成が必要。
※下記作業手順につき、下記を参照した
https://qiita.com/chima91/items/0cd46b5965e087609ef5

1. gsutilをインストール
2. cors.jsonを作成したディレクトリで以下を実行
`gsutil cors set cors.json gs://************.appspot.com`

# やったこと
## 契約書modelの作成

firestoreでは下記スキーマでデータを格納。
```js
 {
     contractId: int,
     title: text,
     pdf: text,
     createdAt: Timestamp,
     alarts: [
         {
             article: text,
             content: text
         },
         ...
     ]
 }
```
CRUDのうちCreate部分（契約書追加）は未作成。

## 一覧ページの作成
![image](https://github.com/koooommmm/contract-checker/assets/86104476/fb12bebb-5c08-409f-9e0f-c8eb2c53dd8c)

※削除ボタンの挙動は未実装。

## 詳細ページの作成
![image](https://github.com/koooommmm/contract-checker/assets/86104476/41b3dd5d-e7b1-4d29-809c-16c772461937)

※今のところこのページから何かを編集することは想定しておらず。

2024-05-05 14:06 UTC, koooommmm requested changes

2024-05-05 14:06 UTC, koooommmm commented on frontend/package.json
> +    "firestore": "^1.1.6",
firebaseパッケージに含まれるfirestoreを使えば良いので、firestoreパッケージは不要かと思います。
下記は非公式のパッケージの気がします。
https://www.npmjs.com/package/firestore

2024-05-05 14:06 UTC, koooommmm commented on frontend/package.json
> +    "vite-plugin-static-copy": "^1.0.4"
`vite-plugin-static-copy`は必要なのでしょうか？
今ひとつ必要性が分からなかったので入れている理由があれば教えていただきたいです。

2024-05-05 14:06 UTC, koooommmm commented on frontend/vite.config.js
ここで設定している内容が今ひとつ分かりませんでした...
`vite-plugin-static-copy`の必要性に関連した内容でしょうか？

2024-05-05 14:06 UTC, koooommmm commented on frontend/src/components/common/ContractsList.jsx
> +const contractsList = await getContractsList();
トップレベルのawaitはビルド時にエラーになるため、下記のようにuseEffect内で非同期関数で取得する方が良いと思います。
```
  // 非同期関数でデータを取得し、`contractsList`にセット
  useEffect(() => {
    const fetchContracts = async () => {
      const contracts = await getContractsList();
      setContractsList(contracts);
    };
```

2024-05-05 14:06 UTC, koooommmm commented on frontend/src/components/common/ContractsList.jsx
> +                })}
keyプロパティが無いため下記のようなWarningが出ています。
```
ContractsList.jsx:68 Warning: Each child in a list should have a unique "key" prop
```

item.idをkeyとして入れるのが良い気がします。
```
<tbody>
          {contractsList.map((item, index) => (
            <ContractRow
              key={item.id} // 各行にユニークなkeyを追加
              index={index}
              id={item.id}
              title={item.title}
              createdAt={item.createdAt}
              isEditing={editingIndex === index}
              setEditingIndex={setEditingIndex}
            />
          ))}
        </tbody>
```

2024-05-05 14:09 UTC, koooommmm commented
コードフォーマッターは何か使われていますでしょうか？
自分は[Prettier](https://prettier.io/)を入れているので、特にこだわりが無ければ合わせられると良いなと思いました。

2024-05-05 14:10 UTC, koooommmm commented
linterを確認すると下記のエラーが出ているので合わせて確認いただければ幸いです。

```
$ docker compose exec frontend npm run lint

> frontend@0.0.0 lint
> eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0


/usr/src/app/src/components/common/ContractDetail.jsx
  57:12  error  'numPages' is assigned a value but never used       no-unused-vars
  58:24  error  'setPageNumber' is assigned a value but never used  no-unused-vars

/usr/src/app/src/components/common/ContractRow.jsx
  16:46  error  'title' is missing in props validation            react/prop-types
  17:27  error  'isEditing' is missing in props validation        react/prop-types
  18:35  error  'setEditingIndex' is missing in props validation  react/prop-types
  23:27  error  'index' is missing in props validation            react/prop-types
  28:71  error  'id' is missing in props validation               react/prop-types
  38:62  error  'index' is missing in props validation            react/prop-types
  43:77  error  'title' is missing in props validation            react/prop-types
  46:69  error  'id' is missing in props validation               react/prop-types
  55:48  error  'createdAt' is missing in props validation        react/prop-types

/usr/src/app/src/components/common/ContractsList.jsx
  38:28  error  Missing "key" prop for element in iterator  react/jsx-key

✖ 12 problems (12 errors, 0 warnings)
```

2024-05-06 23:16 UTC, hmatsunobu commented on frontend/package.json
> +    "firestore": "^1.1.6",
たしかに、`firebase/firestore`からimportしているので不要でした、失礼しました。こちら削除します。

2024-05-06 23:29 UTC, hmatsunobu commented on frontend/package.json
> +    "vite-plugin-static-copy": "^1.0.4"
説明不足で申し訳ありません。`frontend/vite.config.js`の方にて説明します。

2024-05-06 23:34 UTC, hmatsunobu commented on frontend/vite.config.js
こちら説明させていただきます。
前提として、今回は下記ライブラリを使用しています。
https://github.com/wojtekmaj/react-pdf

このライブラリは、漢字や特殊文字を正しくレンダリングするためにcMapsをプロジェクトに導入しなければならず、その際にvite-plugin-static-copyが必要となり、これに関する設定を追記した、という経緯があります。
（上記READMEの中のSupport for non-latin charactersという項にて詳しく説明されています）

こちらコメントなどで記録を残すべき箇所でした、次回より漏れのないようにします。

2024-05-06 23:35 UTC, hmatsunobu commented on frontend/src/components/common/ContractsList.jsx
> +const contractsList = await getContractsList();
こちら完全に当方のミスです。失礼しました。ご提案いただいた形に書き直したいと思います。ありがとうございます。

2024-05-06 23:39 UTC, hmatsunobu commented on frontend/src/components/common/ContractsList.jsx
> +                })}
ありがとうございます。こちらご提案の通りでkey属性追加しようと思います。

2024-05-06 23:51 UTC, hmatsunobu commented
不手際が多く本当にすみません、また、隅々まで見ていただいてありがとうございます。
フォーマッターに関してこだわりはないのでprettierを導入したいと思います。
また、eslintですが、jsxが漏れておりました。諸々のエラーの方修正したいと思います。

2024-05-07 00:51 UTC, hmatsunobu commented
取り急ぎ、修正箇所をpushしましたので、ご確認ください。よろしくお願いします。

2024-05-07 14:12 UTC, koooommmm commented
コメント対応ありがとうございます！
pull して起動してみたのですが、firestore宛に大量にリクエストが飛んでいるようなのですが心当たりってありますか...？（添付）

<img width="1592" alt="image" src="https://github.com/koooommmm/contract-checker/assets/124126985/01b7b1eb-19cd-4371-bc70-d01e46a89756">

2024-05-09 11:58 UTC, hmatsunobu commented
> コメント対応ありがとうございます！ pull して起動してみたのですが、firestore宛に大量にリクエストが飛ぶようになっているのですが心当たりってありますか...？ 修正前の[0853ecfc8c2dde7b3bc613d59a8648ba7af6dca5](https://github.com/koooommmm/contract-checker/pull/17/commits/0853ecfc8c2dde7b3bc613d59a8648ba7af6dca5)の時点では大量リクエストは飛んでいないようです。

こちら、useEffectの第二引数を指定しておらず、任意のstateやpropsが変更されるたびにuseEffectの内容が叩かれ、レンダリングされ、の無限ループになっていたようでした。
取り急ぎ修正の上pushしました。

2024-05-09 12:25 UTC, koooommmm approved these changes

2024-05-09 12:25 UTC, merged